# This message provides convenience options for setting planning scene
# properties such as switching collisions/on off
# These settings are only used for the given motion plan
# and do not cause permanent changes to the planning scene

CollisionPair[] allowed_collision_pairs

CollisionPair[] forbidden_collision_pairs

bool allow_left_hand_environment_collision

bool allow_right_hand_environment_collision

string[] allow_hands_collision_with_object_id